apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - date
          restartPolicy: OnFailure
